// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgzrqrbskywexpnxtgkq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnenJxcmJza3l3ZXhwbnh0Z2txIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NjcyMTEsImV4cCI6MjA3MDA0MzIxMX0.TZ-8hat6i_e8sevLeX7KsLrVVmALe2TOv-59SawjMaw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});